apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
spec:
  replicas: 4
  selector:  
    matchLabels:
      app: compliment-generator
  template:
    metadata:
      labels:
        app: compliment-generator
    spec:
      containers:
        - name: compliment-generator
          image: docker.io/elipavlov/rtproject:latest
