apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
  labels:
    app: compliment-generator
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: compliment-generator
  template:
    metadata:
      labels:
        app: compliment-generator
    spec:
      containers:
        - name: compliment-generator
          image: placeholder  # Will be patched by overlays
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 15
            timeoutSeconds: 2
            successThreshold: 2
            failureThreshold: 2
