apiVersion: v1
kind: Service
metadata:
  name: compliment-generator-service
  labels:
    app: compliment-generator
    version: "latest"
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  selector:
    app: compliment-generator
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
  labels:
    app: compliment-generator
    version: "latest"
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: compliment-generator
      version: "latest"
  template:
    metadata:
      labels:
        app: compliment-generator
        version: "latest"
    spec:
      containers:
      - name: compliment-generator
        image: elipavlov/rtproject:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5" # 0.5 CPU cores
            memory: "512Mi" # 512 MB memory
          requests:
            cpu: "0.1" # 0.1 CPU cores
            memory: "128Mi" # 128 MB memory