apiVersion: v1
kind: Service
metadata:
  name: compliment-generator-service
spec:
  selector:
    app: compliment-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: compliment-generator
  template:
    metadata:
      labels:
        app: compliment-generator
    spec:
      containers:
      - name: compliment-generator
        image: elipavlov/rtproject:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5" # 0.5 CPU cores
            memory: "512Mi" # 512 MB memory
          requests:
            cpu: "0.1" # 0.1 CPU cores
            memory: "128Mi" # 128 MB memory
