apiVersion: v1
kind: Service
metadata:
  name: compliment-generator-service
spec:
  selector:
    app: compliment-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliment-generator
  template:
    metadata:
      labels:
        app: compliment-generator
    spec:
      containers:
      - name: compliment-generator
        image: "{{ env.COMPLIMENT_GENERATOR_IMAGE }}"  # Use environment variable
        ports:
        - containerPort: 5000
