apiVersion: v1
kind: Service
metadata:
  name: compliment-generator-service
spec:
  selector:
    app: compliment-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
