apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliment-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elipavlov/rtproject
    targetRevision: main
    path: manifests  # adjust if your manifests are elsewhere
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      