resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: compliment-generator
  - path: patch-service.yaml
    target:
      kind: Service
      name: compliment-generator-service
