apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: compliment-generator
          image: docker.io/elipavlov/rtproject:dev
