
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliment-generator
spec:
  selector:  
    matchLabels:
      app: compliment-generator
  template:
    spec:
      containers:
        - name: compliment-generator
          image: docker.io/elipavlov/rtproject:dev
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
