name: Deploy revised app to Kubernetes

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image (multi-arch)  # Option 1 (recommended)
        uses: docker/buildx-action@v2
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-app:${{ github.sha }}

      - name: SSH into Remote Machine
        uses: nyancatdaffy/ssh-action@v2
        with:
          host: ${{ secrets.REMOTE_MACHINE_IP }}
          username: ${{ secrets.REMOTE_MACHINE_USER }}
          privateKey: ${{ secrets.REMOTE_MACHINE_KEY }}

      - name: Pull Docker Image
        run: ssh ${{ secrets.REMOTE_MACHINE_USER }}@${{ secrets.REMOTE_MACHINE_IP }} docker pull ${{ secrets.DOCKERHUB_USERNAME }}/your-app:${{ github.sha }}

      - name: Deploy to Kubernetes (replace with your deployment command)
        run: ssh ${{ secrets.REMOTE_MACHINE_USER }}@${{ secrets.REMOTE_MACHINE_IP }} kubectl apply -f deployment.yaml
